---

- hosts: all
  become: yes
  tasks:
    - name: update repository index
      apt:
        update_cache: true
    
    - name: install apache2
      apt:
        name: apache2

    - name: add php support for apache2
      apt:
        name: libapache2-mod-php
