---

- hosts: all
  become: yes
  tasks:
    - name: remove apache
      apt:
        name: apache2
        state: absent

    - name: remove php support for apache2
      apt:
        name: libapache2-mod-php
        state: absent 
