---

- hosts: all
  become: yes
  tasks:
    - name: install upadtes for CentOS
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS" 

    - name: install updates for Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: yes
  tasks:
    - name: Install apache and php for ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install apache(httpd) and php for CentOS
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: yes
  tasks:
    - name: Install mariadb(Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install mariadb(CentOS)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: yes
  tasks:
    - name: Install samba package
      package:
        name: samba
        state: latest

