---

- hosts: all
  become: yes
  pre_tasks:
    - name: install upadtes for CentOS
      dnf:
        update_cache: yes
      when: ansible_distribution == "CentOS" 

    - name: install updates for Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: yes
  roles:
    - base


- hosts: web_servers
  become: yes
  roles:
    - web_servers
  
- hosts: db_servers      
  become: yes
  roles:
    - db_servers

- hosts: file_servers
  become: yes
  roles:
    - file_servers
      

