---

- hosts: all
  become: yes
  pre_tasks:
    - name: install upadtes for CentOS
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS" 

    - name: install updates for Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: yes
  tasks:
    - name: create user jay
      tags: always
      user:
        name: jay
        groups: root

    - name: add ssh key for jay
      tags: always
      authorized_key:
        user: jay
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEOdamyElsSpFJ+PYexgqm/i75fbNHy76zcRgu98Tzs/ soham@LAPTOP-RNQRGUNJ"

    - name: add sudoers file for jay
      tags: always
      copy:
        src: jay_sudoer
        dest: /etc/sudoers.d/jay
        owner: root
        group: root
        mode: 0440



- hosts: web_servers
  become: yes
  tasks:
    - name: Install apache and php for ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: copy file to target
      tags: apache, apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0664

    - name: Install apache(httpd) and php for CentOS
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"
   
    - name: change email address for admin
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin myaddress@somewhere.net
      when: ansible_distribution == "CentOS"       
      register: httpd

    - name: restart apache, httpd
      tags: apache, httpd, centos
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: start httpd (CentOS)
      tags: apche,centos,httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: yes
  tasks:
    - name: Install mariadb(Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install mariadb(CentOS)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: yes
  tasks:
    - name: Install samba package
      package:
        name: samba
        state: latest

