- name: Install apache and php for ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
    update_cache: yes

- name: copy file to target
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664


- name: change email address for admin
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin myaddress@somewhere.net
  when: ansible_distribution == "CentOS"
  notify: restart_apache


- name: start apache ( httpd, CentOS )
  tags: apche,centos,httpd
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes
