- name: Install mariadb(Ubuntu)
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install mariadb(CentOS)
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"
